#!/bin/sh
#
# tool to automate the adding of a new repository

repo="$1"
[ "$repo" = "" ] && printf "::  Repo location: " && read -r repo

name=$(basename "$repo")
[ -d "$name" ] || git clone --bare "$repo" || exit 1

owner="$(whoami)"
url="$(hostname)"
desc=""

# get owner
printf "::  Owner [%s] : " "$owner"
read -r REPLY
[ "$REPLY" = "" ] || owner=$REPLY

# get url
printf "::  URL [%s] : " "$url"
read -r REPLY
[ "$REPLY" = "" ] || url=$REPLY

# get description
printf "::  Description : "
read -r REPLY
[ "$REPLY" = "" ] || desc=$REPLY

echo "$owner" > "$name"/owner
echo "$url" > "$name"/url
echo "$desc" > "$name"/description
