#!/bin/sh
#
# tool to automate the adding of a new repository

# get the repo url
repo="$1"
[ "$repo" = "" ] && printf "::  Repo location: " && read -r repo

# get the repo
name=$(basename "$repo")
[ -d "$name" ] || git clone --bare "$repo" || exit 1

# get owner
owner="$(whoami)"
printf "::  Owner [%s] : " "$owner"
read -r REPLY
[ "$REPLY" = "" ] || owner=$REPLY

# get url
host="$(hostname)"
printf "::  Host git://[%s]/%s: " "$host" "$name"
read -r REPLY
[ "$REPLY" = "" ] || host="$REPLY"
url="git://$host/$name"
echo "::  $url"

# get description
desc=""
printf "::  Description : "
read -r REPLY
[ "$REPLY" = "" ] || desc=$REPLY

# add the metadata to the repo
echo "$owner" > "$name"/owner
echo "$url" > "$name"/url
echo "$desc" > "$name"/description

# get local repos location
path="/srv/git/"
printf "::  Path [%s] : " "$path"
read -r REPLY
[ "$REPLY" = "" ] || path="$REPLY"

# move to the git file path
mv "$name" "$path"
