#!/bin/sh
#
# tool to attempt to automate the deployment of
# a static website

repos="/srv/git"
www="/srv/www"

[ -d "$www" ] || ( echo "folder does not exist!" && exit 1 )

cp -r lib/ "$www"

cd $www || exit 1

stagit-index "$repos"/* > index.html
ln -s lib/style.css .

for i in "$repos"/*; do
	j=$(basename "$i" .git)

	[ -d "$j" ] || mkdir "$j"
	cd "$j" || exit 1

	stagit "$i"
	ln -s ../lib/style.css .

	cd ..
done
