#!/bin/sh
#
# tool to update any given repo

# where are the repos kept
repos="/srv/git"
# where should the html files be
www="/srv/www"
# repo to update
rep="$1"

# check if rep has been assigned
[ "$rep" = "" ] && { echo "::  please enter the name of a repo" && exit 1; }
# check if the repo exists
[ -d "$repos/$rep" ] || { echo "::  repo \"$rep\" does not exist in $repos" && exit 1; }
# if the directories don't exist, exit
if [ -d "$www" ] && [ -d "$repos" ]; then
	echo "::  $www does not exist!" && exit 1;
fi

# update the landing page
stagit-index "$repos"/* > index.html

# generate repo pages
cd "$(basename "$rep" .git)"
stagit "$repos/$rep"
